/*

CRIAÇÃO DE UM SISTEMA DE GERENCIAMENTO DE UMA BIBLIOTECA 
OBJETIVO: CRIAR UM BANCO PARA ARMAZENAR INFORMAÇÕES: 
SOBRE LIVROS, AUTORES, USUÁRIOS E EMPRESTIMOS.

- TABELAS:
USUÁRIOS (ID, NOME, EMAIL, TELEFONE)
LIVROS (ID, TÍTULO, GÊNERO, AUTOR, EDITORA, ANO DE PUBLICAÇÃO)
AUTORES (ID, NOME, NACIONALIDADE),
EDITORAS(ID,NOME)
CATEGORIAS (ID, NOME)
EMPRÉSTIMOS(ID, IDLIVRO, IDUSUAIO, RETIRADA,DEVOLUCAO)


RELACIONAMENTO 1 : N ENTRE LIVROS E AUTORES - UM AUTOR PODE TER VÁRIOS LIVROS. 
ISSO SIGNIFICA QUE A TABELA LIVROS DEVE TER UMA CHAVE ESTRANGEIRA (ID_AUTOR) 
REFERENCIANDO A TABELA AUTORES.

RELACIONAMENTO 1 : N ENTRE LIVROS E EDITORAS - UMA EDITORA PODE PUBLICAR VÁRIOS LIVROS.
NESSE CASO, A TABELA LIVROSDEVE TER UMA CHAVE ESTRANGEIRA ( ID_EDITORA)
 REFERENCIANDO A TABELA EDITORASEDITORAS.

RELACIONAMENTO 1 :N  ENTRE USUÁRIOS E EMPRÉSTIMOS :NEMPRESTIMOSDEVECHAV
E ESTRANGEIRA (ID_ID_USUARIO) REFERIRUSUÁRIOS.

/*


#CRIANDO O BANCO DE DADOS */
CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

#TABELA DE USUÁRIOS: ARMAZENA INFORMAÇÕES DE USUÁRIOS QUE PODEM FAZER EMPRÉSTIMOS 
CREATE TABLE USUARIOS (
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    SEXO ENUM('F','M'),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20));


#TABELA DE AUTORES: ARMAZENA INFORMAÇÕES SOBRE OS AUTORES 
CREATE TABLE AUTORES (
    IDAUTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    NACIONALIDADE CHAR(2));



#TABELA DE EDITORAS: ARMAZENA INFORMAÇÕES SOBRE EDITORAS */
CREATE TABLE EDITORAS (
    IDEDITORA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL);



/*TABELA DE LIVROS: ARMAZENA AS INFORMAÇÕES DE LIVROS, 
COM REFERÊNCIAS PARA TABELAS AUTORES, EDITORAS E CATEGORIAS */
CREATE TABLE LIVROS (
    IDLIVRO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(150) NOT NULL,
    CATEGORIA VARCHAR (150),
    ANOPUBLICACAO SMALLINT NOT NULL, # TIPO DE TIPAGEM QUE SUPORTA ANOS MAIS ANTIGOS 
    ID_EDITORA INT NOT NULL,
    ID_AUTOR INT NOT NULL,

    FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(IDAUTOR),
    FOREIGN KEY (ID_EDITORA) REFERENCES EDITORAS(IDEDITORA));


/* TABELA DE EMPRÉSTIMOS: ARMAZENA AS INFORMAÇÕES SOBRE OS EMPRÉSTIMOS DOS LIVROS.
    CADA EMPRÉSTIMO ESTÁ VINCULADO A UM LIVRO E UM USUÁRIO, COM AS DATAS DE RETIRADA E DEVOLUÇÃO. */
CREATE TABLE EMPRESTIMOS (
    IDEMPRESTIMO INT PRIMARY KEY AUTO_INCREMENT,
    RETIRADA DATE NOT NULL,
    DEVOLUCAO DATE DEFAULT NULL,
    STATUS ENUM('EMPRESTADO', 'DEVOLVIDO'),
    ID_LIVRO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
   
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(IDLIVRO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(IDUSUARIO));


SHOW TABLES;

#VERIFICANDO A CRIAÇÃO DE TODAS AS TABELAS 
+----------------------+
| Tables_in_biblioteca |
+----------------------+
| autores              |
| editoras             |
| emprestimos          |
| livros               |
| usuarios             |
+----------------------+

/* INSERÇÃO DE USUÁRIOS */
INSERT INTO USUARIOS (NOME, SEXO,  EMAIL, TELEFONE) VALUES
('ALICE GOMES', 'F','ALICEGG@GMAIL.COM', '1234567890'),
('BRUNO OLIVEIRA','M', 'BRUNINHO@HOTMAIL.COM', '2345678901'),
('CARLA PEREIRA', 'F', 'CARLAPPEREIRA11@GMAIL.COM', '3456789012'),
('DANIEL COSTA', 'M', 'COSTADANIEEL@GMAIL.COM', '4567890123'),
('EDUARDA LIMA','F', 'DUDINHA1998@HTMAIL.COM', '5678901234'),
('FELIPE ALMEIDA','M','LIPEALMEIDA22@GMAIL.COM', '6789012345'),
('GABRIELA MARTINS','F','GABYMARTINS@GMAIL.COM', '7890123456'),
('HUGO ROCHA','M','HUGOROCHHA@HOTMAIL.COM', '8901234567'),
('ISABELA SILVA', 'F', 'ISASSILVA@GMAIL.COM', '9012345678'),
('JOÃO SOUZA','M', 'JOAOSOUZA@EHOTMAIL.COM', '0123456789'),
('KARINA MENDES','F','KARINAMENDES@YAHOO.COM', '1230987654'),
('LUCAS OLIVEIRA','M','LUCASOLIVEIRA@GMAIL.COM', '2341098765'),
('MARIANA COSTA','F', 'MARIANACOSTA@GMAIL.COM', '3452109876'),
('NATÁLIA PINTO', 'F', 'NATALIA2000@GMAILCOM', '4563210987'),
('OTÁVIO FERNANDES', 'M','OTAVIOFF@GMAIL.COM', '5674321098');


SELECT * FROM USUARIOS;
#MOSTRAR TODOS OS USUARIOS
+-----------+------------------+------+---------------------------+------------+
| IDUSUARIO | NOME             | SEXO | EMAIL                     | TELEFONE   |
+-----------+------------------+------+---------------------------+------------+
|         1 | ALICE GOMES      | F    | ALICEGG@GMAIL.COM         | 1234567890 |
|         2 | BRUNO OLIVEIRA   | M    | BRUNINHO@HOTMAIL.COM      | 2345678901 |
|         3 | CARLA PEREIRA    | F    | CARLAPPEREIRA11@GMAIL.COM | 3456789012 |
|         4 | DANIEL COSTA     | M    | COSTADANIEEL@GMAIL.COM    | 4567890123 |
|         5 | EDUARDA LIMA     | F    | DUDINHA1998@HTMAIL.COM    | 5678901234 |
|         6 | FELIPE ALMEIDA   | M    | LIPEALMEIDA22@GMAIL.COM   | 6789012345 |
|         7 | GABRIELA MARTINS | F    | GABYMARTINS@GMAIL.COM     | 7890123456 |
|         8 | HUGO ROCHA       | M    | HUGOROCHHA@HOTMAIL.COM    | 8901234567 |
|         9 | ISABELA SILVA    | F    | ISASSILVA@GMAIL.COM       | 9012345678 |
|        10 | JOÃO SOUZA       | M    | JOAOSOUZA@EHOTMAIL.COM    | 0123456789 |
|        11 | KARINA MENDES    | F    | KARINAMENDES@YAHOO.COM    | 1230987654 |
|        12 | LUCAS OLIVEIRA   | M    | LUCASOLIVEIRA@GMAIL.COM   | 2341098765 |
|        13 | MARIANA COSTA    | F    | MARIANACOSTA@GMAIL.COM    | 3452109876 |
|        14 | NATÁLIA PINTO    | F    | NATALIA2000@GMAILCOM      | 4563210987 |
|        15 | OTÁVIO FERNANDES | M    | OTAVIOFF@GMAIL.COM        | 5674321098 |
+-----------+------------------+------+---------------------------+------------+



/* INSERÇÃO DE AUTORES */
INSERT INTO AUTORES (NOME, NACIONALIDADE) VALUES
('RAINBOW ROWELL', 'US'), 
('J.K. ROWLING', 'GB'),  
('AGATHA CHRISTIE', 'GB'),
('J.R.R. TOLKIEN', 'GB'), 
('STEPHEN KING', 'US'),
('MARK TWAIN', 'US'),
('ISAAC ASIMOV', 'RU'),
('CHARLES DICKENS', 'GB'),
('HARPER LEE', 'US'),
('GABRIEL GARCÍA MÁRQUEZ', 'CO'),
('HOMER', 'GR'),
('KENTARO MIURA', 'JP'), 
('STAN LEE', 'US'),
('BILL FINGER', 'US'),
('F. SCOTT FITZGERALD', 'US'),
('LUO GUANZHONG', 'CN'),
('VIRGINIA WOOLF', 'GB'),
('ERNEST HEMINGWAY', 'US'),
('OSCAR WILDE', 'IE'),
('DOUGLAS PRESTON', 'US'),
('JOSÉ SARAMAGO', 'BR'),
('CLARICE LISPECTOR', 'BR'),
('MACHADO DE ASSIS', 'BR'),
('CAIO FERNANDO ABREU', 'BR'),
('PAULO COELHO', 'BR');

/* INSERÇÃO DE EDITORAS */
INSERT INTO EDITORAS (NOME) VALUES
('EDITORA GLOBO'),
('HARPERCOLLINS'),
('COMPANHIA DAS LETRAS'),
('RECORD'),
('ROCCO'),
('LEYA'),
('ARQUEIRO'),
('CIA. DAS LETRAS'),
('SUMA DE LETRAS'),
('INTRÍNSECA'),
('ALEPH'),
('OBJETIVA'),
('ZAHAR'),
('PENGUIN RANDOM HOUSE'),
('VIKING'),
('L&PM'),
('PANINI'),
('MARVEL COMICS'),
('DC COMICS');




/* INSERÇÃO DE LIVROS */
INSERT INTO LIVROS (TITULO, ID_AUTOR, ID_EDITORA, ANOPUBLICACAO, CATEGORIA) VALUES
('HARRY POTTER E A PEDRA FILOSOFAL', 2, 1, 1997, 'FICCAO'),
('O ROMANCE DOS TRES REINOS', 1, 2, 1394, 'FICCAO'), 
('MURDER ON THE ORIENT EXPRESS', 3, 3, 1934, 'MISTERIO'),
('O SENHOR DOS ANEIS: A SOCIEDADE DO ANEL', 4, 4, 1954, 'AVENTURA'),
('O ILUMINADO', 5, 5, 1977, 'MISTERIO'),
('AS AVENTURAS DE TOM SAWYER', 6, 6, 1876, 'SATIRICO'),
('FUNDACAO', 7, 7, 1951, 'FICCAO CIENTIFICA'),
('OLIVER TWIST', 8, 8, 1837, 'CLASSICO'),
('O SOL E PARA TODOS', 9, 9, 1960, 'DRAMA'),
('CEM ANOS DE SOLIDAO', 10, 10, 1967, 'REALISMO MAGICO'),
('A ILIADA', 11, 11, 1992, 'CLASSICO'), 
('O GRANDE GATSBY', 12, 12, 1925, 'FICCAO'),
('MRS. DALLOWAY', 13, 13, 1925, 'MODERNISMO'),
('A REVOLUCAO DOS BICHOS', 22, 1, 1945, 'SATIRICO'),
('WATCHMEN', 10, 2, 1986, 'HQ'),
('O VELHO E O MAR', 14, 14, 1952, 'MISTERIO'),
('O RETRATO DE DORIAN GRAY', 15, 15, 1890, 'FICCAO'),
('ELEANOR & PARK', 10, 1, 2012, 'FICCAO'),
('FANGIRL', 10, 1, 2013, 'FICCAO'),
('CARRY ON', 10, 1, 2015, 'FICCAO'),
('A CIDADE PERDIDA DO DEUS MACACO', 10, 1, 2017, 'AVENTURA'),
('ENSAYO SOBRE LA CEGUERA', 10, 4, 1995, 'CLASSICO'),
('O EVANGELHO SEGUNDO JESUS CRISTO', 10, 4, 1991, 'CLASSICO'),
('A HORA DA ESTRELA', 10, 1, 1977, 'FICCAO'),
('DOM CASMURRO', 10, 1, 1899, 'FICCAO'),
('MEMORIAS POSTUMAS DE BRAZ CUBAS', 10, 4, 1881, 'CLASSICO'),
('O ALQUIMISTA', 10, 1, 1988, 'FICCAO'),
('THE DARK KNIGHT RETURNS', 18, 2, 1986, 'HQ'),
('SANDMAN', 19, 2, 1989, 'HQ'),
('V FOR VENDETTA', 20, 2, 1982, 'HQ'),
('BERSERK', 21, 12, 1989, 'MANGA'),
('SPIDER MAN', 22, 2, 1962, 'HQ'),
('SHAZAM', 23, 19, 1939, 'HQ');




/* INSERÇÃO DE EMPRESTIMOS */
INSERT INTO EMPRESTIMOS (ID_LIVRO, ID_USUARIO, RETIRADA, DEVOLUCAO, STATUS) VALUES
(1, 1, '2025-02-01', NULL, 'EMPRESTADO'),
(2, 2, '2025-02-03', NULL, 'EMPRESTADO'),
(3, 3, '2025-02-05', NULL, 'EMPRESTADO'),
(4, 4, '2025-02-07', NULL, 'EMPRESTADO'),
(5, 5, '2025-02-09', '2025-02-16', 'DEVOLVIDO'),
(6, 6, '2025-02-10', NULL, 'EMPRESTADO'),
(7, 7, '2025-02-12', NULL, 'EMPRESTADO'),
(8, 8, '2025-02-14', '2025-02-20', 'DEVOLVIDO'),
(9, 9, '2025-02-15', NULL, 'EMPRESTADO'),
(10, 10, '2025-02-17', NULL, 'EMPRESTADO'),
(11, 11, '2025-02-18', '2025-02-25', 'DEVOLVIDO'),
(12, 12, '2025-02-19', NULL, 'EMPRESTADO'),
(13, 13, '2025-02-20', NULL, 'EMPRESTADO'),
(14, 14, '2025-02-22', NULL, 'EMPRESTADO'),
(15, 15, '2025-02-24', NULL, 'EMPRESTADO');


-------------------------------------------------
#CRIANDO SCRIPTS DE CONSULTA

#VERIFICANDO QUAIS SÃO LIVROS ESTÃO ENTRE (BETEWEEN) 1997 E (AND) 2025 

SELECT  
    IDLIVRO AS CODIGO,  
    TITULO AS "TITULO",  
    ANOPUBLICACAO AS "ANO DE PUBLICACAO",  
    CATEGORIA AS "CATEGORIA"  
FROM LIVROS  
WHERE ANOPUBLICACAO BETWEEN 1997 AND 2025;

--------+----------------------------------+-------------------+-----------+
| CODIGO | TITULO                           | ANO DE PUBLICACAO | CATEGORIA |
+--------+----------------------------------+-------------------+-----------+
|      1 | HARRY POTTER E A PEDRA FILOSOFAL |              1997 | FICCAO    |
|     18 | ELEANOR & PARK                   |              2012 | FICCAO    |
|     19 | FANGIRL                          |              2013 | FICCAO    |
|     20 | CARRY ON                         |              2015 | FICCAO    |
|     21 | A CIDADE PERDIDA DO DEUS MACACO  |              2017 | AVENTURA  |
+--------+----------------------------------+-------------------+-----------+



#CONSULTAR QUANTOS USUARIOS TEM LIVROS EMPRESATANSO
SELECT 
    USUARIOS.NOME AS "USUÁRIO", 
    COUNT(EMPRESTIMOS.IDEMPRESTIMO) AS "NÚMERO DE EMPRÉSTIMOS"
FROM USUARIOS 
INNER JOIN EMPRESTIMOS  ON USUARIOS.IDUSUARIO = EMPRESTIMOS.ID_USUARIO
WHERE EMPRESTIMOS.STATUS = 'EMPRESTADO'
GROUP BY USUARIOS.NOME;


#CONSULTA DELIVROS EMPRESTADOS E SITUAÇÃO DE DEVOLUÇÃO;
SELECT
    L.TITULO AS "TÍTULO DO LIVRO", 
    E.RETIRADA AS "DATA DE RETIRADA", 
    E.DEVOLUCAO AS "DATA DE DEVOLUÇÃO", 
    E.STATUS AS "STATUS DO EMPRÉSTIMO"
FROM EMPRESTIMOS E
INNER JOIN LIVROS L ON E.ID_LIVRO = L.IDLIVRO
WHERE E.STATUS IN ('EMPRESTADO', 'DEVOLVIDO');


-------------------------------------------------

/* O OBJETIVO DA CRIAÇÃO DO RELATÓRIO USANDO O GATILHO TRIGGER, COM A TABELA RELATORIO_LIVROS, 
É REGISTRAR TODAS AS ALTERAÇÕES FEITAS NA TABELA LIVROS, ESPECIFICAMENTE INSERÇÕES DE NOVOS LIVROS. 
UM GATILHO É CONFIGURADO PARA REGISTRAR AUTOMATICAMENTE CADA VEZ QUE UM NOVO LIVRO É INSERIDO, 
CRIANDO UM REGISTRO DE AUDITORIA.

ESSE TIPO DE RELATÓRIO AJUDA A DOCUMENTAR AS AÇÕES NO BANCO DE DADOS, 
GARANTINDO QUE VOCÊ TENHA UM RASTREAMENTO DE AUDITORIAS DAS INSERÇÕES FEITAS, O QUE É ÚTIL PARA MONITORAMENTO, 
ANÁLISE, CONTROLE E TRANSPARÊNCIA EM SISTEMAS DE DADOS. 

 A TABELA RELATORIO_LIVROS FUNCIONA COMO UMA AUDITORIA PARA MONITORAR TODAS AS INSERÇÕES DE LIVROS NO BANCO DE DADOS. 

CADA VEZ QUE UM LIVRO É ADICIONADO À TABELA LIVROS, ACIONA O REGISTRO DOS DADOS E HORA DA INSERÇÃO, 
DA AÇÃO (QUE É SEMPRE "INSERÇÃO" NESTE CASO) E DO TÍTULO DO LIVRO INSERIDO. */


CREATE TABLE RELATORIO_LIVROS (
    IDRELATORIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_LIVRO INT,
    DATA_INSERCAO DATETIME,
    ACAO_TIPO VARCHAR(50),
    TITULO_LIVRO VARCHAR(255),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(IDLIVRO)
);


DELIMITER #

CREATE TRIGGER AFTER_INSERT_LIVRO
AFTER INSERT ON LIVROS
FOR EACH ROW
BEGIN
    INSERT INTO RELATORIO_LIVROS (ID_LIVRO, DATA_INSERCAO, ACAO_TIPO, TITULO_LIVRO)
    VALUES (NEW.IDLIVRO, NOW(), 'INSERÇÃO', NEW.TITULO);
END #

DELIMITER ;


INSERT INTO LIVROS (TITULO, ID_AUTOR, ID_EDITORA, ANOPUBLICACAO, CATEGORIA) VALUES
('HARRY POTTER E O PRISONEIRO DE AZKABAN', 2, 1, 2004, 'FICCAO'),
('X-MEN: DAYS OF FUTURE PAST', 13, 2, 1981, 'HQ'),
('CARRIE', 14, 10, 1394, 'TERROR');

SELECT * FROM RELATORIO_LIVROS;
